### ISSUE TITLE
Game desyncs because client ticks before receiving events

### ISSUE THREAD

**Issue by thomaswp** [thomaswp/BeaverBuddies#1]
**Describe the bug**
* Game desynced after ~20m without a clear cause.
* In the logs, the client kept ticking, without receiving events, and then received 4 at once (at which point it desycned, presumably because the random seed from 4 frames ago didn't match, though it probably hadn't diverged state)

**Logs**: On both the server and client computer, do the following steps:
[desync server.txt](https://github.com/thomaswp/BeaverBuddies/files/14148113/desync.server.txt)

**To Reproduce**: If you have been able to reproduce this bug multiple times, describe the steps (or delete this section)
Cannot currently reproduce. I've tried toggling the wifi to create connection disruptions.

**Desktop (please complete the following information):**
 - OS: Windows 10 / Windows 11
 - Timberborn version: 0.5.9.0
 - BeaverBuddies version: 1.0.0

**Comment by thomaswp** [comment]
[desyncclient.txt](https://github.com/thomaswp/BeaverBuddies/files/14148678/desyncclient.txt)

**Comment by thomaswp** [comment]
I can confirm this behavior is still happening in v1.1.5-beta

**Comment by Cilyena** [comment]
I think it's the same bug: https://github.com/thomaswp/BeaverBuddies/issues/33

**Comment by thomaswp** [comment]
Hopefully fixed with #33!
