### ISSUE TITLE
MacOs & Windows CrossPlay Confirmed

### ISSUE THREAD

**Issue by DistantWorld** [thomaswp/BeaverBuddies#14]
- Host: MacOs Sonoma 14.3.1  Apple M3
- Client: Windows 11
- Second Client: Windows 11
- TimberBornVersion:  v0.5.9.1-33dabbc-sw
- Beaver Buddies: Version: 1.1.4
- Bepindexpack: Version: 5.4.22.1
- ModManger Version: Version: 2.0.0
- TimberAPI: Version: 0.6.5.0

Played for multiple hours with "compromise(_note blow)_" trouble.
switching host to a windows and MacOs connecting also worked 

NOTE: this was over VPN
speeding the game up in quick bursts then pausing for cpl seconds then play works fine, having it sped up longer then 30 seconds caused a desync.

NOTE 2: i and willing to do any MAC Os testing  that is needed for i have both Windows machines, Mac Os machines

**Comment by thomaswp** [comment]
Thanks for confirming crossplay! Could you try [v1.15-beta](https://mod.io/g/timberborn/m/beaverbuddies) and see if it fixes your desync issues. If not could you upload your save game here or to the discord so I can reproduce it?

**Comment by thomaswp** [comment]
Closing for now - let me know if you see it again.
