### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Thysos** [thomaswp/BeaverBuddies#16]
**Describe the bug**
* What happened: Crash 
* What were your doing right before this happened?: Just running the game 2x speed. Last we built a fire pit and some stairs and at the moment it crashed we both did nothing, just waited for the buildings to be finished and watched.
* Crash happened yesterday in hamachi too, today we didn't use hamachi (same network so it worked also without.)

**Desktop (please complete the following information for **both** Host and Client):**
- Information same on both Host and Client:
 - OS: Windows 11
 - Timberborn version: 0.5.9.1-33dabbc-sw
 - BeaverBuddies version: 1.1.5 beta
[Server.log](https://github.com/thomaswp/BeaverBuddies/files/14825074/Server.log)
[Timberborns own error report.zip](https://github.com/thomaswp/BeaverBuddies/files/14825084/Timberborns.own.error.report.zip)
[client.log](https://github.com/thomaswp/BeaverBuddies/files/14825234/client.log)

**Comment by Thysos** [comment]
[Server.log](https://github.com/thomaswp/BeaverBuddies/files/14825998/Server.log)

Another Crash 10 minutes later

**Comment by thomaswp** [comment]
Thanks for the report. The logs are very helpful. I'll definitely look into it. Seems like you ran into the same thing as #15.  I don't understand how it's happening, so I'll need some time to try to reproduce it. 

This may be the product of changes I made in the latest patch, so you could try an older version if it keeps happening in the meantime.

**Comment by joseprl89** [comment]
@thomaswp I dont think there was anything v significant, we had a couple of districts going on, and we were doing the early game (planting trees, farms,...). I think as the colony grew it was more common (I assume as we were planting more often?).

I'm not sure how a mod is built, but am wondering if you can replace the dictionary with a thread safe one, or if there's a "if it doesn't exist insert if not don't do anything"

**Comment by thomaswp** [comment]
@joseprl89 there are definitely a number of fixes I could apply to solve the "symptom" so to speak, but I worried that just skipping invalid guids will cause desyncs and other major issues. I'd rather be able to reproduce and then fix it in a way I can confirm works, rather than just a workaround. That's why I was asking if any of your saves reliably produce the error.

But if nothing else I can try that in the next release.

**Comment by thomaswp** [comment]
Further checking of the logs shows that it can't be the same random guid being generated twice, since I also log that. I'm quite stumped on this one...

**Comment by Thysos** [comment]
> A few questions for both @Thysos and @joseprl89:
> 
> * Is there a save file you have that reproduces this behavior reliably? 
- No the crashes seem to be totally random every 10-15 minutes. 
> * Did anything notable happen before the crash? 
- Nothing.
> * Did both client and server crash, or just one? 
- First the server crashes while the client freezes then after a few seconds the client crashes too (this happens everytime when it crashes)
> * Was anyone trying to rejoin at the time (guessing not from the logs)? 
- No

**Comment by thomaswp** [comment]
Ok, I figured it out. Since guids are also saved in the save file, it's occurring because the same guid is being generated again when you load that file. I've got a fix and just need to test and release it. Thanks for your help.

**Comment by thomaswp** [comment]
Ok, the fix is live. Let me know if you're still getting the crash.

**Comment by joseprl89** [comment]
Hi @thomaswp we were able to play for a bit, at some point the game desynced, and now when we try to join the match, the client crashes and the server freezes. I don't have a crash report on the server, but sharing the client one.

Attaching also the save file in case it helps.

[error-report-2024-04-06-18h16m26s.zip](https://github.com/thomaswp/BeaverBuddies/files/14894176/error-report-2024-04-06-18h16m26s.zip)

[37BB18A9.zip](https://github.com/thomaswp/BeaverBuddies/files/14894180/37BB18A9.zip)

**Comment by thomaswp** [comment]
Ugh. Ok, well this is interesting. Apparently upon loading the game, Timberborn immediately checks whether any beavers should be procreating... and so a child is born before the server can send the correct random seed. Not sure why they do that, but look like I'll have to change my strategy a bit. I know how to fix it, but it'll involve fiddling with the networking because I'll have to send the random seed along with the map, so it'll need some testing. Thanks for your continued help testing!

**Comment by joseprl89** [comment]
No worries, happy to do tests when new versions are ready too!

**Comment by Thysos** [comment]
We played a few hours yesterday with your new version. The Game didn't crash once (but desynced).The desyncs seemed very random, sometimes after 30 minutes (and more), sometimes every 2 minutes and then after a few desyncs again nothing for a longer period. 
It's way better than before because resyncing the Game means a short loading screen without restarting the whole Game! Thanks for your great work!

**Comment by Lillemats90** [comment]
ive written a comment in #13 about this issue, we are desyncing immediately now when joining the save.

**Comment by thomaswp** [comment]
Ok, thanks everyone for your input and your log data and saves. I think I've fixed it for real this time, since I was able to reproduce the issue locally and confirm the fix. But as always, I'll need your help testing. Try [v1.1.7-beta](https://mod.io/g/timberborn/m/beaverbuddies) and let me know if it fixes it.

**Comment by joseprl89** [comment]
@thomaswp thanks a lot! We managed to play for a while with no crashes, only desyncs. We noticed the desyncs would happen about the same time when we had a weird tide effect that would flood some builds at semi-regular intervals, wondering if that flooding event would trigger too many syncs across the network and bottleneck or something? In any case, thanks a lot for your help!

**Comment by Lillemats90** [comment]
> Try [v1.1.7-beta]

We will test it the next few days :)

**Comment by thomaswp** [comment]
I'm going to close since I haven't seen this pop up in comments or issues since the release, but let me know if it happens again.
