### ISSUE TITLE
Desync at a random time after my friend join the game

### ISSUE THREAD

**Issue by xSaii5** [thomaswp/BeaverBuddies#19]
Host and Client 
 - OS: Windows 11 
 - Timberborn version: v0.5.9.1-33dabbc-sw
 - BeaverBuddies version: v1.1.7-beta

Hello,

Immediately after my friend join the game I host on hamachi, there is an error who says that a player has been desync.

please find the log attached and the screenshot of the error message
![screenshot](https://github.com/thomaswp/BeaverBuddies/assets/169206554/94fc1572-1152-4efb-8a95-fcd896c2cd8f)
[client.txt](https://github.com/thomaswp/BeaverBuddies/files/15241129/client.txt)
[server.log](https://github.com/thomaswp/BeaverBuddies/files/15241130/server.log)

**Comment by thomaswp** [comment]
Hi, I've recently fixed a number of desync issues in v1.1.8. Please update BeaverBuddies, and if the problem persists, please upload your save file so I can replicate it.
