### ISSUE TITLE
Crash upon path confirmation box popup (pause related?)

### ISSUE THREAD

**Issue by peoplearestrange** [thomaswp/BeaverBuddies#20]
**Describe the bug**
Just started game. Working fine and syncing. Game was unpaused.

We were placing paths, then when I went to remove some paths, as soon as the diaglouge box asking for confirmation of demolition popped up my buddy got de-sync.

**To Reproduce**: If you have been able to reproduce this bug multiple times, describe the steps (or delete this section)
1. Start game.
2. client connects
3. unpause game
4. place path
5. remove path
6. dialogue box pop up (pausing the game automatically)
7. de-sync

**Desktop (please complete the following information for **both** Host and Client):**
 - OS: win10 pro
 - Timberborn version: V0.5.9.1
 - BeaverBuddies version: 22/05/2024
[server.txt](https://github.com/thomaswp/BeaverBuddies/files/15408504/server.txt)

**Comment by peoplearestrange** [comment]
[client.txt](https://github.com/thomaswp/BeaverBuddies/files/15408564/client.txt)
Clients log as well

**Comment by thomaswp** [comment]
Thanks for posting! I'll look into. It may be a little while. Let me know if it's happening consistently.

**Comment by thomaswp** [comment]
Actually, let me ask a clarification - was this a crash or a desync? Did the game actually freeze, or just the client was disconnected and you had to reconnect? If it was a desync, then I think it's likely fixed in v1.1.8, so please try updating and let me know if it persists.

**Comment by thomaswp** [comment]
Hey, I haven't heard back from you, so I'll close this. My focus right now is on supporting Update 6. If you're still having the issue, please reopen and post you save file in a .zip folder.
