### ISSUE TITLE
Desync with Analytics enabled checked (guid desync)

### ISSUE THREAD

**Issue by Cilyena** [thomaswp/BeaverBuddies#31]
V1.22 for Update V6

> **Edit 3 hours after, i found an Workaround :** https://github.com/thomaswp/BeaverBuddies/issues/31#issuecomment-2312341785
> I have rename the issue

The game desyncs in a few minutes with no action after loading a new game save (with no buildings, nothing).

It's a NewGuid problem :

```
File DeterminismService.cs
Class GuidPatcher
Function Prefix
Line 788 - 796
```

When we use GenerateIncrementally instead of GenerateWithUnityRandom, no Desync.

**Comment by Cilyena** [comment]
![image](https://github.com/user-attachments/assets/1c48d919-4caf-45e9-a16c-09bb66bf37cc)

**Comment by Cilyena** [comment]
With GenerateWithUnityRandom + Empty World :

![image](https://github.com/user-attachments/assets/8e896fbc-a5ed-43dc-8b97-37f88c7b31e7)

**Comment by Cilyena** [comment]
I found the problem. The data collection is probably generating a GUID locally and causing the desync. By unchecking this option, I have no more desync with empty world & GUID.

![image](https://github.com/user-attachments/assets/f2030d3f-96e3-4ee5-bd64-8896d3718881)

**Comment by Cilyena** [comment]
![image](https://github.com/user-attachments/assets/2b87101b-64a0-45c7-bdfc-36846e53f451)

I confirm

**Comment by thomaswp** [comment]
Thanks for posting. I don't see anything the Analytics namespace that looks like it is using Random or Guid, but let me know if you see something. It could be that Unity's Analytics classes use Guid - actually seems pretty likely, so I'll try to reproduce the error. I don't have analytics enabled myself, so that might be why I haven't gotten this.

**Comment by thomaswp** [comment]
Update: It's definitely the Analytics service - good find! Testing a fix now.

**Comment by thomaswp** [comment]
I'm getting some other desyncs as well, often at the very start of the game, that seem to go away without analytics, so I may need to look deeper.
