### ISSUE TITLE
Broken BepInEx setup link in wiki

### ISSUE THREAD

**Issue by ST-DDT** [thomaswp/BeaverBuddies#35]
The link is broken:

https://timberapi.com/using_mods/manual_install/

on:

https://github.com/thomaswp/BeaverBuddies/wiki/Installation-and-Running -> `Modding Setup (BepInEx)`

**Comment by thomaswp** [comment]
Thanks, this is due to changes in how mods work starting soon when Update 6 releases. I've updated the installation instructions accordingly!
