### ISSUE TITLE
Game desyncs after 20mins

### ISSUE THREAD

**Issue by denizfishy** [thomaswp/BeaverBuddies#37]
Ive been playing multiplayer with a friend of mine for quite some time now. The game "crashes" every time after around 20mins of playing (by crashing i mean desyncing with the rehost popup if u know what i mean). Btw we are not placing a specific building or anything it always crashes after 20mins of playing (even if we are just afk).

(github says the file type isnt supported if i try to upload the save file)

ServerLog: 
[server.log](https://github.com/user-attachments/files/16966886/server.log)

Server ErrorReport (idk if u need that):
[error-report-2024-09-11-18h34m53s.zip](https://github.com/user-attachments/files/16966897/error-report-2024-09-11-18h34m53s.zip)

ClientLog:
[client.log](https://github.com/user-attachments/files/16966889/client.log)

We are both using Windows 10.
Timberborn version: 0.5.9.1 (both)
BeaverBuddies version: 1.1.7 in the logs but we both have 1.1.8 installed

**Comment by denizfishy** [comment]
now my game crahes after i place something down. (before this the game was still desyncing after 5-20mins btw)

ServerLog:
[server.log](https://github.com/user-attachments/files/17007377/server.log)

Server ErrorReport:
[error-report-2024-09-15-22h40m35s.zip](https://github.com/user-attachments/files/17007380/error-report-2024-09-15-22h40m35s.zip)

**Comment by thomaswp** [comment]
Thanks for posting @denizfishy and sharing the save file! Right now I'm primarly working on supporting Update 6, which will release in 5 days - since the code changed a lot and may fix issues from the Update 5. See if the issue still persists then, and if so please post again!
