### ISSUE TITLE
Game desync

### ISSUE THREAD

**Issue by KevDev2002** [thomaswp/BeaverBuddies#38]
The game desyncs after a certain amount of time or when i remove resources such as blueberrys or trees

**Comment by thomaswp** [comment]
Hi @KevDev2002 , please see the [instructions for posting an issue](https://github.com/thomaswp/BeaverBuddies/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). I'll need more information to help you.

**Comment by thomaswp** [comment]
Ok, you were completely right about marking resources for destruction causing a desync - great catch. I think it's fixed in the newest release on Update 6 (v.1.2.5). Let me know if so.

Also, there may be other desyncs related to water - that's in #7 . Still working on it.
