### ISSUE TITLE
Kick Client back to Main Menu on desync

### ISSUE THREAD

**Issue by L0ric0** [thomaswp/BeaverBuddies#9]
**Describe what you want the mod to be able to do**
When a Desync happens the Client should be kicked back to the Main Menu.

**Describe alternatives you've considered**
Alternatively the mod could automatically save the game on the Host, reload it and auto join the client on desync.
Another alternative would be to leave the game running on the Client so that it can save the game or play alone. This would have the added benefit to be able to recover to the current state of the game if the host crashes.

**Additional context**
Currently desyncs can happen quite frequently and the Client is left unable to do anything in the Game other that forcequiting by Alt+F4 or other means. This is a mayor anoyance.

**Comment by thomaswp** [comment]
Good idea. I thought that I'd fixed the client no longer being able to act in 1.1.3, but it should be fixed now in 1.1.4. I've also added buttons on the desync message to auto reconnect for host and client.
